optimizer_name: adamw

lr: 1e-4
betas:
  - 0.9
  - 0.98
weight_decay: 5e-4

lr_scheduler: 
  warmup_name: linear
  warmup_lr_factor: 0.1
  warmup_num_epochs_ratio: 0.05
  name: cosine
  T_max: ${trainer.max_epochs}
  eta_min: 1e-6