# _target_: pytorch_lightning.Trainer

max_epochs: 100            
accelerator: "auto"       
devices: "auto"           
precision: 16-mixed
# gradient_clip_val: 0.5 
log_every_n_steps: 5     
check_val_every_n_epoch: 1 
accumulate_grad_batches: 32

total_num_devices: 1
fast_dev_run: False
# deterministic: True    

score_threshold: 0.5  
resume_from_ckpt_path: null
