# _target_: pytorch_lightning.Trainer

max_epochs: 30            
accelerator: "auto"       
devices: "auto"           
precision: 16-mixed
# gradient_clip_val: 0.5 
log_every_n_steps: 50     
check_val_every_n_epoch: 1 
accumulate_grad_batches: 16 
fast_dev_run: False  
# deterministic: True    

score_threshold: 0.5  
resume_from_ckpt_path: null
